# General Code style/formatting checks
name: Linting

on:
  pull_request:

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          # Cache is branch-scope, but the cache will shared across workflows if they reuse this key
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: yarn --frozen-lockfile --prefer-offline

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn eslint

  commitlint:
    name: Commitlint
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # required to get all history, not just commit that triggers current run
        with:
          fetch-depth: 0

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - uses: wagoid/commitlint-github-action@v2
        with:
          configFile: .commitlintrc.js
